#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

COUNTER=1
while [ $COUNTER -lt 101 ]
do 
   if [ $((COUNTER%15)) = 0 ]
   then
	echo "FizzBuzz"
   elif [ $((COUNTER%3)) = 0 ]
   then
	echo "Fizz"
   else
	echo "$COUNTER"
   fi
   (( COUNTER+=1 ))
done
