#!/usr/bin/env bash
# script loops from 1 to 10
# displays bad luck on 4th loop
# displays good luck on 8th loop
# displays Best School for the other loops
i=1
while [[ $i -le 10 ]]; do
    if [ $i -eq 4 ]; then
	echo "bad luck"
    elif [ $i -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i+=1 ))
done 
