#!/usr/bin/env bash
# this script will display the time for 12 hours 59 mins
# display hours from 0 to 12
# displays minutes from 1 to 59

h=0
m=1
while [ $h -le 12 ]; do
    echo "Hour: ${h}"
    while [ $m -lt 60 ]; do
	echo $m
	(( m+=1 ))
    done
    (( m=1 ))
    (( h+=1))
done
